// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Pigeon equivalent of the iOS QGVAPWrapViewContentMode.
enum PlatformContentMode {
  scaleToFill,
  aspectFit,
  aspectFill,
}

/// Pigeon equivalent of VapResourceType.
enum PlatformResourceType {
  image,
  text,
}

class PlatformCreationOptions {
  PlatformCreationOptions({
    required this.enableFrameEvents,
  });

  bool enableFrameEvents;

  List<Object?> _toList() {
    return <Object?>[
      enableFrameEvents,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformCreationOptions decode(Object result) {
    result as List<Object?>;
    return PlatformCreationOptions(
      enableFrameEvents: result[0]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCreationOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(enableFrameEvents, other.enableFrameEvents);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCreationOptions(enableFrameEvents: $enableFrameEvents)';
  }
}

class PlatformPlayOptions {
  PlatformPlayOptions({
    required this.path,
    required this.repeatCount,
    required this.mute,
    required this.contentMode,
    required this.enableOldVersion,
  });

  String path;

  /// 0 = play once, n = play n+1 times, -1 = loop forever.
  int repeatCount;

  bool mute;

  PlatformContentMode contentMode;

  /// Enables playback of plain alpha mp4s without a `vapc` box.
  bool enableOldVersion;

  List<Object?> _toList() {
    return <Object?>[
      path,
      repeatCount,
      mute,
      contentMode,
      enableOldVersion,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformPlayOptions decode(Object result) {
    result as List<Object?>;
    return PlatformPlayOptions(
      path: result[0]! as String,
      repeatCount: result[1]! as int,
      mute: result[2]! as bool,
      contentMode: result[3]! as PlatformContentMode,
      enableOldVersion: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformPlayOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) && _deepEquals(repeatCount, other.repeatCount) && _deepEquals(mute, other.mute) && _deepEquals(contentMode, other.contentMode) && _deepEquals(enableOldVersion, other.enableOldVersion);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformPlayOptions(path: $path, repeatCount: $repeatCount, mute: $mute, contentMode: $contentMode, enableOldVersion: $enableOldVersion)';
  }
}

/// A VAPX mix resource placeholder.
class PlatformVapResource {
  PlatformVapResource({
    required this.id,
    required this.type,
    required this.tag,
  });

  String id;

  PlatformResourceType type;

  String tag;

  List<Object?> _toList() {
    return <Object?>[
      id,
      type,
      tag,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformVapResource decode(Object result) {
    result as List<Object?>;
    return PlatformVapResource(
      id: result[0]! as String,
      type: result[1]! as PlatformResourceType,
      tag: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformVapResource || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(type, other.type) && _deepEquals(tag, other.tag);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformVapResource(id: $id, type: $type, tag: $tag)';
  }
}

sealed class PlatformVapEvent {
}

/// Sent when the vapc config is parsed, right before rendering starts.
class ConfigReadyEvent extends PlatformVapEvent {
  ConfigReadyEvent({
    required this.width,
    required this.height,
    required this.videoWidth,
    required this.videoHeight,
    required this.frameCount,
    required this.fps,
    required this.isMix,
  });

  int width;

  int height;

  int videoWidth;

  int videoHeight;

  int frameCount;

  int fps;

  bool isMix;

  List<Object?> _toList() {
    return <Object?>[
      width,
      height,
      videoWidth,
      videoHeight,
      frameCount,
      fps,
      isMix,
    ];
  }

  Object encode() {
    return _toList();  }

  static ConfigReadyEvent decode(Object result) {
    result as List<Object?>;
    return ConfigReadyEvent(
      width: result[0]! as int,
      height: result[1]! as int,
      videoWidth: result[2]! as int,
      videoHeight: result[3]! as int,
      frameCount: result[4]! as int,
      fps: result[5]! as int,
      isMix: result[6]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConfigReadyEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) && _deepEquals(height, other.height) && _deepEquals(videoWidth, other.videoWidth) && _deepEquals(videoHeight, other.videoHeight) && _deepEquals(frameCount, other.frameCount) && _deepEquals(fps, other.fps) && _deepEquals(isMix, other.isMix);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ConfigReadyEvent(width: $width, height: $height, videoWidth: $videoWidth, videoHeight: $videoHeight, frameCount: $frameCount, fps: $fps, isMix: $isMix)';
  }
}

/// Sent when the first frame is rendered.
class StartedEvent extends PlatformVapEvent {
  StartedEvent();

  List<Object?> _toList() {
    return <Object?>[
    ];
  }

  Object encode() {
    return _toList();  }

  static StartedEvent decode(Object result) {
    result as List<Object?>;
    return StartedEvent(
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StartedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    return true;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StartedEvent()';
  }
}

/// Sent per rendered frame, only when enableFrameEvents was requested.
class FrameRenderedEvent extends PlatformVapEvent {
  FrameRenderedEvent({
    required this.frameIndex,
  });

  int frameIndex;

  List<Object?> _toList() {
    return <Object?>[
      frameIndex,
    ];
  }

  Object encode() {
    return _toList();  }

  static FrameRenderedEvent decode(Object result) {
    result as List<Object?>;
    return FrameRenderedEvent(
      frameIndex: result[0]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FrameRenderedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(frameIndex, other.frameIndex);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'FrameRenderedEvent(frameIndex: $frameIndex)';
  }
}

/// Sent when playback finishes (all repeats done, or stopped).
class CompletedEvent extends PlatformVapEvent {
  CompletedEvent();

  List<Object?> _toList() {
    return <Object?>[
    ];
  }

  Object encode() {
    return _toList();  }

  static CompletedEvent decode(Object result) {
    result as List<Object?>;
    return CompletedEvent(
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompletedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    return true;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CompletedEvent()';
  }
}

/// Sent when the native player has released its resources.
class DestroyedEvent extends PlatformVapEvent {
  DestroyedEvent();

  List<Object?> _toList() {
    return <Object?>[
    ];
  }

  Object encode() {
    return _toList();  }

  static DestroyedEvent decode(Object result) {
    result as List<Object?>;
    return DestroyedEvent(
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DestroyedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    return true;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DestroyedEvent()';
  }
}

/// Sent when playback fails.
class FailedEvent extends PlatformVapEvent {
  FailedEvent({
    required this.errorType,
    this.errorMsg,
  });

  int errorType;

  String? errorMsg;

  List<Object?> _toList() {
    return <Object?>[
      errorType,
      errorMsg,
    ];
  }

  Object encode() {
    return _toList();  }

  static FailedEvent decode(Object result) {
    result as List<Object?>;
    return FailedEvent(
      errorType: result[0]! as int,
      errorMsg: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FailedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(errorType, other.errorType) && _deepEquals(errorMsg, other.errorMsg);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'FailedEvent(errorType: $errorType, errorMsg: $errorMsg)';
  }
}

/// Sent when a VAPX resource is tapped.
class ResourceClickedEvent extends PlatformVapEvent {
  ResourceClickedEvent({
    required this.resource,
  });

  PlatformVapResource resource;

  List<Object?> _toList() {
    return <Object?>[
      resource,
    ];
  }

  Object encode() {
    return _toList();  }

  static ResourceClickedEvent decode(Object result) {
    result as List<Object?>;
    return ResourceClickedEvent(
      resource: result[0]! as PlatformVapResource,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ResourceClickedEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(resource, other.resource);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ResourceClickedEvent(resource: $resource)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PlatformContentMode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PlatformResourceType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is PlatformCreationOptions) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformPlayOptions) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformVapResource) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is ConfigReadyEvent) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is StartedEvent) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is FrameRenderedEvent) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is CompletedEvent) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is DestroyedEvent) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is FailedEvent) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is ResourceClickedEvent) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformContentMode.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformResourceType.values[value];
      case 131:
        return PlatformCreationOptions.decode(readValue(buffer)!);
      case 132:
        return PlatformPlayOptions.decode(readValue(buffer)!);
      case 133:
        return PlatformVapResource.decode(readValue(buffer)!);
      case 134:
        return ConfigReadyEvent.decode(readValue(buffer)!);
      case 135:
        return StartedEvent.decode(readValue(buffer)!);
      case 136:
        return FrameRenderedEvent.decode(readValue(buffer)!);
      case 137:
        return CompletedEvent.decode(readValue(buffer)!);
      case 138:
        return DestroyedEvent.decode(readValue(buffer)!);
      case 139:
        return FailedEvent.decode(readValue(buffer)!);
      case 140:
        return ResourceClickedEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class IosVapPlayerApi {
  /// Constructor for [IosVapPlayerApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  IosVapPlayerApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_ios.IosVapPlayerApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Creates a player; returns the player id.
  Future<int> create(PlatformCreationOptions options) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_ios.IosVapPlayerApi.create$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<void> dispose(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_ios.IosVapPlayerApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

class VapPlayerInstanceApi {
  /// Constructor for [VapPlayerInstanceApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VapPlayerInstanceApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Starts playback from the first frame.
  Future<void> play(PlatformPlayOptions options) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_ios.VapPlayerInstanceApi.play$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Stops playback.
  Future<void> stop() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_ios.VapPlayerInstanceApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Pauses playback.
  Future<void> pause() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_ios.VapPlayerInstanceApi.pause$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Resumes playback after pause.
  Future<void> resume() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_ios.VapPlayerInstanceApi.resume$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Mutes/unmutes; only takes effect at the next play/loop start.
  Future<void> setMute(bool mute) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_ios.VapPlayerInstanceApi.setMute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mute]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Sets the repeat count for subsequent plays.
  Future<void> setRepeatCount(int repeatCount) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_ios.VapPlayerInstanceApi.setRepeatCount$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[repeatCount]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Tells native whether a Dart resource delegate exists.
  Future<void> setHasResourceDelegate(bool hasDelegate) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_ios.VapPlayerInstanceApi.setHasResourceDelegate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[hasDelegate]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class VapResourceFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<String?> resolveText(int playerId, PlatformVapResource resource);

  Future<Uint8List?> resolveImage(int playerId, PlatformVapResource resource);

  static void setUp(VapResourceFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.vap_player_ios.VapResourceFlutterApi.resolveText$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_playerId = args[0]! as int;
          final PlatformVapResource arg_resource = args[1]! as PlatformVapResource;
          try {
            final String? output = await api.resolveText(arg_playerId, arg_resource);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.vap_player_ios.VapResourceFlutterApi.resolveImage$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_playerId = args[0]! as int;
          final PlatformVapResource arg_resource = args[1]! as PlatformVapResource;
          try {
            final Uint8List? output = await api.resolveImage(arg_playerId, arg_resource);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

/// Returns a broadcast [Stream] of events from the `vapEvents` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<PlatformVapEvent> vapEvents( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel vapEventsChannel =
      EventChannel('dev.flutter.pigeon.vap_player_ios.VapEventChannelApi.vapEvents$instanceName', pigeonMethodCodec);
  return vapEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as PlatformVapEvent;
  });
}
    
