// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum messagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Pigeon equivalent of the iOS QGVAPWrapViewContentMode.
enum PlatformContentMode: Int, CaseIterable {
  case scaleToFill = 0
  case aspectFit = 1
  case aspectFill = 2
}

/// Pigeon equivalent of VapResourceType.
enum PlatformResourceType: Int, CaseIterable {
  case image = 0
  case text = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCreationOptions: Hashable, CustomStringConvertible {
  var enableFrameEvents: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformCreationOptions? {
    let enableFrameEvents = pigeonVar_list[0] as! Bool

    return PlatformCreationOptions(
      enableFrameEvents: enableFrameEvents
    )
  }
  func toList() -> [Any?] {
    return [
      enableFrameEvents
    ]
  }
  static func == (lhs: PlatformCreationOptions, rhs: PlatformCreationOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.enableFrameEvents, rhs.enableFrameEvents)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformCreationOptions")
    messagesPigeonInternal.deepHash(value: enableFrameEvents, hasher: &hasher)
  }

  public var description: String {
    return "PlatformCreationOptions(enableFrameEvents: \(String(describing: enableFrameEvents)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformPlayOptions: Hashable, CustomStringConvertible {
  var path: String
  /// 0 = play once, n = play n+1 times, -1 = loop forever.
  var repeatCount: Int64
  var mute: Bool
  var contentMode: PlatformContentMode
  /// Enables playback of plain alpha mp4s without a `vapc` box.
  var enableOldVersion: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformPlayOptions? {
    let path = pigeonVar_list[0] as! String
    let repeatCount = pigeonVar_list[1] as! Int64
    let mute = pigeonVar_list[2] as! Bool
    let contentMode = pigeonVar_list[3] as! PlatformContentMode
    let enableOldVersion = pigeonVar_list[4] as! Bool

    return PlatformPlayOptions(
      path: path,
      repeatCount: repeatCount,
      mute: mute,
      contentMode: contentMode,
      enableOldVersion: enableOldVersion
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      repeatCount,
      mute,
      contentMode,
      enableOldVersion,
    ]
  }
  static func == (lhs: PlatformPlayOptions, rhs: PlatformPlayOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.path, rhs.path) && messagesPigeonInternal.deepEquals(lhs.repeatCount, rhs.repeatCount) && messagesPigeonInternal.deepEquals(lhs.mute, rhs.mute) && messagesPigeonInternal.deepEquals(lhs.contentMode, rhs.contentMode) && messagesPigeonInternal.deepEquals(lhs.enableOldVersion, rhs.enableOldVersion)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformPlayOptions")
    messagesPigeonInternal.deepHash(value: path, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: repeatCount, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: mute, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: contentMode, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: enableOldVersion, hasher: &hasher)
  }

  public var description: String {
    return "PlatformPlayOptions(path: \(String(describing: path)), repeatCount: \(String(describing: repeatCount)), mute: \(String(describing: mute)), contentMode: \(String(describing: contentMode)), enableOldVersion: \(String(describing: enableOldVersion)))"
  }
}

/// A VAPX mix resource placeholder.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformVapResource: Hashable, CustomStringConvertible {
  var id: String
  var type: PlatformResourceType
  var tag: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformVapResource? {
    let id = pigeonVar_list[0] as! String
    let type = pigeonVar_list[1] as! PlatformResourceType
    let tag = pigeonVar_list[2] as! String

    return PlatformVapResource(
      id: id,
      type: type,
      tag: tag
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      type,
      tag,
    ]
  }
  static func == (lhs: PlatformVapResource, rhs: PlatformVapResource) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.id, rhs.id) && messagesPigeonInternal.deepEquals(lhs.type, rhs.type) && messagesPigeonInternal.deepEquals(lhs.tag, rhs.tag)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformVapResource")
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: tag, hasher: &hasher)
  }

  public var description: String {
    return "PlatformVapResource(id: \(String(describing: id)), type: \(String(describing: type)), tag: \(String(describing: tag)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol PlatformVapEvent {

}

/// Sent when the vapc config is parsed, right before rendering starts.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ConfigReadyEvent: PlatformVapEvent {
  var width: Int64
  var height: Int64
  var videoWidth: Int64
  var videoHeight: Int64
  var frameCount: Int64
  var fps: Int64
  var isMix: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConfigReadyEvent? {
    let width = pigeonVar_list[0] as! Int64
    let height = pigeonVar_list[1] as! Int64
    let videoWidth = pigeonVar_list[2] as! Int64
    let videoHeight = pigeonVar_list[3] as! Int64
    let frameCount = pigeonVar_list[4] as! Int64
    let fps = pigeonVar_list[5] as! Int64
    let isMix = pigeonVar_list[6] as! Bool

    return ConfigReadyEvent(
      width: width,
      height: height,
      videoWidth: videoWidth,
      videoHeight: videoHeight,
      frameCount: frameCount,
      fps: fps,
      isMix: isMix
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
      videoWidth,
      videoHeight,
      frameCount,
      fps,
      isMix,
    ]
  }
  static func == (lhs: ConfigReadyEvent, rhs: ConfigReadyEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.width, rhs.width) && messagesPigeonInternal.deepEquals(lhs.height, rhs.height) && messagesPigeonInternal.deepEquals(lhs.videoWidth, rhs.videoWidth) && messagesPigeonInternal.deepEquals(lhs.videoHeight, rhs.videoHeight) && messagesPigeonInternal.deepEquals(lhs.frameCount, rhs.frameCount) && messagesPigeonInternal.deepEquals(lhs.fps, rhs.fps) && messagesPigeonInternal.deepEquals(lhs.isMix, rhs.isMix)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConfigReadyEvent")
    messagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: height, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: videoWidth, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: videoHeight, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: frameCount, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: fps, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: isMix, hasher: &hasher)
  }

  public var description: String {
    return "ConfigReadyEvent(width: \(String(describing: width)), height: \(String(describing: height)), videoWidth: \(String(describing: videoWidth)), videoHeight: \(String(describing: videoHeight)), frameCount: \(String(describing: frameCount)), fps: \(String(describing: fps)), isMix: \(String(describing: isMix)))"
  }
}

/// Sent when the first frame is rendered.
///
/// Generated class from Pigeon that represents data sent in messages.
struct StartedEvent: PlatformVapEvent {


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StartedEvent? {

    return StartedEvent(
    )
  }
  func toList() -> [Any?] {
    return [
    ]
  }
  static func == (lhs: StartedEvent, rhs: StartedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return true
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StartedEvent")
  }

  public var description: String {
    return "StartedEvent()"
  }
}

/// Sent per rendered frame, only when enableFrameEvents was requested.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FrameRenderedEvent: PlatformVapEvent {
  var frameIndex: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FrameRenderedEvent? {
    let frameIndex = pigeonVar_list[0] as! Int64

    return FrameRenderedEvent(
      frameIndex: frameIndex
    )
  }
  func toList() -> [Any?] {
    return [
      frameIndex
    ]
  }
  static func == (lhs: FrameRenderedEvent, rhs: FrameRenderedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.frameIndex, rhs.frameIndex)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("FrameRenderedEvent")
    messagesPigeonInternal.deepHash(value: frameIndex, hasher: &hasher)
  }

  public var description: String {
    return "FrameRenderedEvent(frameIndex: \(String(describing: frameIndex)))"
  }
}

/// Sent when playback finishes (all repeats done, or stopped).
///
/// Generated class from Pigeon that represents data sent in messages.
struct CompletedEvent: PlatformVapEvent {


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CompletedEvent? {

    return CompletedEvent(
    )
  }
  func toList() -> [Any?] {
    return [
    ]
  }
  static func == (lhs: CompletedEvent, rhs: CompletedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return true
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CompletedEvent")
  }

  public var description: String {
    return "CompletedEvent()"
  }
}

/// Sent when the native player has released its resources.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DestroyedEvent: PlatformVapEvent {


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DestroyedEvent? {

    return DestroyedEvent(
    )
  }
  func toList() -> [Any?] {
    return [
    ]
  }
  static func == (lhs: DestroyedEvent, rhs: DestroyedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return true
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DestroyedEvent")
  }

  public var description: String {
    return "DestroyedEvent()"
  }
}

/// Sent when playback fails.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FailedEvent: PlatformVapEvent {
  var errorType: Int64
  var errorMsg: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FailedEvent? {
    let errorType = pigeonVar_list[0] as! Int64
    let errorMsg: String? = nilOrValue(pigeonVar_list[1])

    return FailedEvent(
      errorType: errorType,
      errorMsg: errorMsg
    )
  }
  func toList() -> [Any?] {
    return [
      errorType,
      errorMsg,
    ]
  }
  static func == (lhs: FailedEvent, rhs: FailedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.errorType, rhs.errorType) && messagesPigeonInternal.deepEquals(lhs.errorMsg, rhs.errorMsg)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("FailedEvent")
    messagesPigeonInternal.deepHash(value: errorType, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: errorMsg, hasher: &hasher)
  }

  public var description: String {
    return "FailedEvent(errorType: \(String(describing: errorType)), errorMsg: \(String(describing: errorMsg)))"
  }
}

/// Sent when a VAPX resource is tapped.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ResourceClickedEvent: PlatformVapEvent {
  var resource: PlatformVapResource


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ResourceClickedEvent? {
    let resource = pigeonVar_list[0] as! PlatformVapResource

    return ResourceClickedEvent(
      resource: resource
    )
  }
  func toList() -> [Any?] {
    return [
      resource
    ]
  }
  static func == (lhs: ResourceClickedEvent, rhs: ResourceClickedEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.resource, rhs.resource)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ResourceClickedEvent")
    messagesPigeonInternal.deepHash(value: resource, hasher: &hasher)
  }

  public var description: String {
    return "ResourceClickedEvent(resource: \(String(describing: resource)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformContentMode(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformResourceType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return PlatformCreationOptions.fromList(self.readValue() as! [Any?])
    case 132:
      return PlatformPlayOptions.fromList(self.readValue() as! [Any?])
    case 133:
      return PlatformVapResource.fromList(self.readValue() as! [Any?])
    case 134:
      return ConfigReadyEvent.fromList(self.readValue() as! [Any?])
    case 135:
      return StartedEvent.fromList(self.readValue() as! [Any?])
    case 136:
      return FrameRenderedEvent.fromList(self.readValue() as! [Any?])
    case 137:
      return CompletedEvent.fromList(self.readValue() as! [Any?])
    case 138:
      return DestroyedEvent.fromList(self.readValue() as! [Any?])
    case 139:
      return FailedEvent.fromList(self.readValue() as! [Any?])
    case 140:
      return ResourceClickedEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PlatformContentMode {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformResourceType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformCreationOptions {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformPlayOptions {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformVapResource {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ConfigReadyEvent {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? StartedEvent {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? FrameRenderedEvent {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? CompletedEvent {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? DestroyedEvent {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? FailedEvent {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? ResourceClickedEvent {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

var messagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MessagesPigeonCodecReaderWriter());

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol IosVapPlayerApi {
  func initialize() throws
  /// Creates a player; returns the player id.
  func create(options: PlatformCreationOptions) throws -> Int64
  func dispose(playerId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class IosVapPlayerApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `IosVapPlayerApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: IosVapPlayerApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_ios.IosVapPlayerApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { _, reply in
        do {
          try api.initialize()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Creates a player; returns the player id.
    let createChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_ios.IosVapPlayerApi.create\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! PlatformCreationOptions
        do {
          let result = try api.create(options: optionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_ios.IosVapPlayerApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.dispose(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VapPlayerInstanceApi {
  /// Starts playback from the first frame.
  func play(options: PlatformPlayOptions) throws
  /// Stops playback.
  func stop() throws
  /// Pauses playback.
  func pause() throws
  /// Resumes playback after pause.
  func resume() throws
  /// Mutes/unmutes; only takes effect at the next play/loop start.
  func setMute(mute: Bool) throws
  /// Sets the repeat count for subsequent plays.
  func setRepeatCount(repeatCount: Int64) throws
  /// Tells native whether a Dart resource delegate exists.
  func setHasResourceDelegate(hasDelegate: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VapPlayerInstanceApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `VapPlayerInstanceApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VapPlayerInstanceApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Starts playback from the first frame.
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_ios.VapPlayerInstanceApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! PlatformPlayOptions
        do {
          try api.play(options: optionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    /// Stops playback.
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_ios.VapPlayerInstanceApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    /// Pauses playback.
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_ios.VapPlayerInstanceApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { _, reply in
        do {
          try api.pause()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    /// Resumes playback after pause.
    let resumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_ios.VapPlayerInstanceApi.resume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeChannel.setMessageHandler { _, reply in
        do {
          try api.resume()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resumeChannel.setMessageHandler(nil)
    }
    /// Mutes/unmutes; only takes effect at the next play/loop start.
    let setMuteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_ios.VapPlayerInstanceApi.setMute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMuteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let muteArg = args[0] as! Bool
        do {
          try api.setMute(mute: muteArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMuteChannel.setMessageHandler(nil)
    }
    /// Sets the repeat count for subsequent plays.
    let setRepeatCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_ios.VapPlayerInstanceApi.setRepeatCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setRepeatCountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let repeatCountArg = args[0] as! Int64
        do {
          try api.setRepeatCount(repeatCount: repeatCountArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setRepeatCountChannel.setMessageHandler(nil)
    }
    /// Tells native whether a Dart resource delegate exists.
    let setHasResourceDelegateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_ios.VapPlayerInstanceApi.setHasResourceDelegate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setHasResourceDelegateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let hasDelegateArg = args[0] as! Bool
        do {
          try api.setHasResourceDelegate(hasDelegate: hasDelegateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setHasResourceDelegateChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol VapResourceFlutterApiProtocol {
  func resolveText(playerId playerIdArg: Int64, resource resourceArg: PlatformVapResource, completion: @escaping (Result<String?, PigeonError>) -> Void)
  func resolveImage(playerId playerIdArg: Int64, resource resourceArg: PlatformVapResource, completion: @escaping (Result<FlutterStandardTypedData?, PigeonError>) -> Void)
}
class VapResourceFlutterApi: VapResourceFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func resolveText(playerId playerIdArg: Int64, resource resourceArg: PlatformVapResource, completion: @escaping (Result<String?, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.vap_player_ios.VapResourceFlutterApi.resolveText\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([playerIdArg, resourceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        let result: String? = nilOrValue(listResponse[0])
        completion(.success(result))
      }
    }
  }
  func resolveImage(playerId playerIdArg: Int64, resource resourceArg: PlatformVapResource, completion: @escaping (Result<FlutterStandardTypedData?, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.vap_player_ios.VapResourceFlutterApi.resolveImage\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([playerIdArg, resourceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        let result: FlutterStandardTypedData? = nilOrValue(listResponse[0])
        completion(.success(result))
      }
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class VapEventsStreamHandler: PigeonEventChannelWrapper<PlatformVapEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: VapEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.vap_player_ios.VapEventChannelApi.vapEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<PlatformVapEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
