// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsVapPlayerMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashVapPlayerMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsVapPlayerMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsVapPlayerMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsVapPlayerMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsVapPlayerMessages(lhsKey, rhsKey) {
          if deepEqualsVapPlayerMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsVapPlayerMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashVapPlayerMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashVapPlayerMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashVapPlayerMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashVapPlayerMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashVapPlayerMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashVapPlayerMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum VapSourceTypeMessage: Int {
  case asset = 0
  case file = 1
  case network = 2
}

enum VapContentModeMessage: Int {
  case scaleToFill = 0
  case aspectFit = 1
  case aspectFill = 2
}

enum VapPlaybackEventTypeMessage: Int {
  case configReady = 0
  case start = 1
  case frame = 2
  case complete = 3
  case destroy = 4
  case stopped = 5
  case failed = 6
}

/// Generated class from Pigeon that represents data sent in messages.
struct VapPlayRequestMessage: Hashable {
  var viewId: Int64? = nil
  var sourceType: VapSourceTypeMessage? = nil
  var source: String? = nil
  var assetPackage: String? = nil
  var repeatCount: Int64? = nil
  var mute: Bool? = nil
  var contentMode: VapContentModeMessage? = nil
  var fps: Int64? = nil
  var frameEventsEnabled: Bool? = nil
  var tagValues: [String?: String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VapPlayRequestMessage? {
    let viewId: Int64? = nilOrValue(pigeonVar_list[0])
    let sourceType: VapSourceTypeMessage? = nilOrValue(pigeonVar_list[1])
    let source: String? = nilOrValue(pigeonVar_list[2])
    let assetPackage: String? = nilOrValue(pigeonVar_list[3])
    let repeatCount: Int64? = nilOrValue(pigeonVar_list[4])
    let mute: Bool? = nilOrValue(pigeonVar_list[5])
    let contentMode: VapContentModeMessage? = nilOrValue(pigeonVar_list[6])
    let fps: Int64? = nilOrValue(pigeonVar_list[7])
    let frameEventsEnabled: Bool? = nilOrValue(pigeonVar_list[8])
    let tagValues: [String?: String?]? = nilOrValue(pigeonVar_list[9])

    return VapPlayRequestMessage(
      viewId: viewId,
      sourceType: sourceType,
      source: source,
      assetPackage: assetPackage,
      repeatCount: repeatCount,
      mute: mute,
      contentMode: contentMode,
      fps: fps,
      frameEventsEnabled: frameEventsEnabled,
      tagValues: tagValues
    )
  }
  func toList() -> [Any?] {
    return [
      viewId,
      sourceType,
      source,
      assetPackage,
      repeatCount,
      mute,
      contentMode,
      fps,
      frameEventsEnabled,
      tagValues,
    ]
  }
  static func == (lhs: VapPlayRequestMessage, rhs: VapPlayRequestMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsVapPlayerMessages(lhs.viewId, rhs.viewId) && deepEqualsVapPlayerMessages(lhs.sourceType, rhs.sourceType) && deepEqualsVapPlayerMessages(lhs.source, rhs.source) && deepEqualsVapPlayerMessages(lhs.assetPackage, rhs.assetPackage) && deepEqualsVapPlayerMessages(lhs.repeatCount, rhs.repeatCount) && deepEqualsVapPlayerMessages(lhs.mute, rhs.mute) && deepEqualsVapPlayerMessages(lhs.contentMode, rhs.contentMode) && deepEqualsVapPlayerMessages(lhs.fps, rhs.fps) && deepEqualsVapPlayerMessages(lhs.frameEventsEnabled, rhs.frameEventsEnabled) && deepEqualsVapPlayerMessages(lhs.tagValues, rhs.tagValues)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VapPlayRequestMessage")
    deepHashVapPlayerMessages(value: viewId, hasher: &hasher)
    deepHashVapPlayerMessages(value: sourceType, hasher: &hasher)
    deepHashVapPlayerMessages(value: source, hasher: &hasher)
    deepHashVapPlayerMessages(value: assetPackage, hasher: &hasher)
    deepHashVapPlayerMessages(value: repeatCount, hasher: &hasher)
    deepHashVapPlayerMessages(value: mute, hasher: &hasher)
    deepHashVapPlayerMessages(value: contentMode, hasher: &hasher)
    deepHashVapPlayerMessages(value: fps, hasher: &hasher)
    deepHashVapPlayerMessages(value: frameEventsEnabled, hasher: &hasher)
    deepHashVapPlayerMessages(value: tagValues, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VapPlaybackEventMessage: Hashable {
  var viewId: Int64? = nil
  var type: VapPlaybackEventTypeMessage? = nil
  var frameIndex: Int64? = nil
  var width: Int64? = nil
  var height: Int64? = nil
  var fps: Int64? = nil
  var isMix: Bool? = nil
  var errorCode: Int64? = nil
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VapPlaybackEventMessage? {
    let viewId: Int64? = nilOrValue(pigeonVar_list[0])
    let type: VapPlaybackEventTypeMessage? = nilOrValue(pigeonVar_list[1])
    let frameIndex: Int64? = nilOrValue(pigeonVar_list[2])
    let width: Int64? = nilOrValue(pigeonVar_list[3])
    let height: Int64? = nilOrValue(pigeonVar_list[4])
    let fps: Int64? = nilOrValue(pigeonVar_list[5])
    let isMix: Bool? = nilOrValue(pigeonVar_list[6])
    let errorCode: Int64? = nilOrValue(pigeonVar_list[7])
    let errorMessage: String? = nilOrValue(pigeonVar_list[8])

    return VapPlaybackEventMessage(
      viewId: viewId,
      type: type,
      frameIndex: frameIndex,
      width: width,
      height: height,
      fps: fps,
      isMix: isMix,
      errorCode: errorCode,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      viewId,
      type,
      frameIndex,
      width,
      height,
      fps,
      isMix,
      errorCode,
      errorMessage,
    ]
  }
  static func == (lhs: VapPlaybackEventMessage, rhs: VapPlaybackEventMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsVapPlayerMessages(lhs.viewId, rhs.viewId) && deepEqualsVapPlayerMessages(lhs.type, rhs.type) && deepEqualsVapPlayerMessages(lhs.frameIndex, rhs.frameIndex) && deepEqualsVapPlayerMessages(lhs.width, rhs.width) && deepEqualsVapPlayerMessages(lhs.height, rhs.height) && deepEqualsVapPlayerMessages(lhs.fps, rhs.fps) && deepEqualsVapPlayerMessages(lhs.isMix, rhs.isMix) && deepEqualsVapPlayerMessages(lhs.errorCode, rhs.errorCode) && deepEqualsVapPlayerMessages(lhs.errorMessage, rhs.errorMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VapPlaybackEventMessage")
    deepHashVapPlayerMessages(value: viewId, hasher: &hasher)
    deepHashVapPlayerMessages(value: type, hasher: &hasher)
    deepHashVapPlayerMessages(value: frameIndex, hasher: &hasher)
    deepHashVapPlayerMessages(value: width, hasher: &hasher)
    deepHashVapPlayerMessages(value: height, hasher: &hasher)
    deepHashVapPlayerMessages(value: fps, hasher: &hasher)
    deepHashVapPlayerMessages(value: isMix, hasher: &hasher)
    deepHashVapPlayerMessages(value: errorCode, hasher: &hasher)
    deepHashVapPlayerMessages(value: errorMessage, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VapResourceClickEventMessage: Hashable {
  var viewId: Int64? = nil
  var resourceId: String? = nil
  var tag: String? = nil
  var x: Double? = nil
  var y: Double? = nil
  var width: Double? = nil
  var height: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VapResourceClickEventMessage? {
    let viewId: Int64? = nilOrValue(pigeonVar_list[0])
    let resourceId: String? = nilOrValue(pigeonVar_list[1])
    let tag: String? = nilOrValue(pigeonVar_list[2])
    let x: Double? = nilOrValue(pigeonVar_list[3])
    let y: Double? = nilOrValue(pigeonVar_list[4])
    let width: Double? = nilOrValue(pigeonVar_list[5])
    let height: Double? = nilOrValue(pigeonVar_list[6])

    return VapResourceClickEventMessage(
      viewId: viewId,
      resourceId: resourceId,
      tag: tag,
      x: x,
      y: y,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      viewId,
      resourceId,
      tag,
      x,
      y,
      width,
      height,
    ]
  }
  static func == (lhs: VapResourceClickEventMessage, rhs: VapResourceClickEventMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsVapPlayerMessages(lhs.viewId, rhs.viewId) && deepEqualsVapPlayerMessages(lhs.resourceId, rhs.resourceId) && deepEqualsVapPlayerMessages(lhs.tag, rhs.tag) && deepEqualsVapPlayerMessages(lhs.x, rhs.x) && deepEqualsVapPlayerMessages(lhs.y, rhs.y) && deepEqualsVapPlayerMessages(lhs.width, rhs.width) && deepEqualsVapPlayerMessages(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VapResourceClickEventMessage")
    deepHashVapPlayerMessages(value: viewId, hasher: &hasher)
    deepHashVapPlayerMessages(value: resourceId, hasher: &hasher)
    deepHashVapPlayerMessages(value: tag, hasher: &hasher)
    deepHashVapPlayerMessages(value: x, hasher: &hasher)
    deepHashVapPlayerMessages(value: y, hasher: &hasher)
    deepHashVapPlayerMessages(value: width, hasher: &hasher)
    deepHashVapPlayerMessages(value: height, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VapImageResolveRequestMessage: Hashable {
  var viewId: Int64? = nil
  var resourceId: String? = nil
  var tag: String? = nil
  var type: String? = nil
  var loadType: String? = nil
  var width: Int64? = nil
  var height: Int64? = nil
  var url: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VapImageResolveRequestMessage? {
    let viewId: Int64? = nilOrValue(pigeonVar_list[0])
    let resourceId: String? = nilOrValue(pigeonVar_list[1])
    let tag: String? = nilOrValue(pigeonVar_list[2])
    let type: String? = nilOrValue(pigeonVar_list[3])
    let loadType: String? = nilOrValue(pigeonVar_list[4])
    let width: Int64? = nilOrValue(pigeonVar_list[5])
    let height: Int64? = nilOrValue(pigeonVar_list[6])
    let url: String? = nilOrValue(pigeonVar_list[7])

    return VapImageResolveRequestMessage(
      viewId: viewId,
      resourceId: resourceId,
      tag: tag,
      type: type,
      loadType: loadType,
      width: width,
      height: height,
      url: url
    )
  }
  func toList() -> [Any?] {
    return [
      viewId,
      resourceId,
      tag,
      type,
      loadType,
      width,
      height,
      url,
    ]
  }
  static func == (lhs: VapImageResolveRequestMessage, rhs: VapImageResolveRequestMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsVapPlayerMessages(lhs.viewId, rhs.viewId) && deepEqualsVapPlayerMessages(lhs.resourceId, rhs.resourceId) && deepEqualsVapPlayerMessages(lhs.tag, rhs.tag) && deepEqualsVapPlayerMessages(lhs.type, rhs.type) && deepEqualsVapPlayerMessages(lhs.loadType, rhs.loadType) && deepEqualsVapPlayerMessages(lhs.width, rhs.width) && deepEqualsVapPlayerMessages(lhs.height, rhs.height) && deepEqualsVapPlayerMessages(lhs.url, rhs.url)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VapImageResolveRequestMessage")
    deepHashVapPlayerMessages(value: viewId, hasher: &hasher)
    deepHashVapPlayerMessages(value: resourceId, hasher: &hasher)
    deepHashVapPlayerMessages(value: tag, hasher: &hasher)
    deepHashVapPlayerMessages(value: type, hasher: &hasher)
    deepHashVapPlayerMessages(value: loadType, hasher: &hasher)
    deepHashVapPlayerMessages(value: width, hasher: &hasher)
    deepHashVapPlayerMessages(value: height, hasher: &hasher)
    deepHashVapPlayerMessages(value: url, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VapImageResolveResultMessage: Hashable {
  var imageBytes: FlutterStandardTypedData? = nil
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VapImageResolveResultMessage? {
    let imageBytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[0])
    let errorMessage: String? = nilOrValue(pigeonVar_list[1])

    return VapImageResolveResultMessage(
      imageBytes: imageBytes,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      imageBytes,
      errorMessage,
    ]
  }
  static func == (lhs: VapImageResolveResultMessage, rhs: VapImageResolveResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsVapPlayerMessages(lhs.imageBytes, rhs.imageBytes) && deepEqualsVapPlayerMessages(lhs.errorMessage, rhs.errorMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VapImageResolveResultMessage")
    deepHashVapPlayerMessages(value: imageBytes, hasher: &hasher)
    deepHashVapPlayerMessages(value: errorMessage, hasher: &hasher)
  }
}

private class VapPlayerMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VapSourceTypeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VapContentModeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VapPlaybackEventTypeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return VapPlayRequestMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return VapPlaybackEventMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return VapResourceClickEventMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return VapImageResolveRequestMessage.fromList(self.readValue() as! [Any?])
    case 136:
      return VapImageResolveResultMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class VapPlayerMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? VapSourceTypeMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? VapContentModeMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? VapPlaybackEventTypeMessage {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? VapPlayRequestMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? VapPlaybackEventMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? VapResourceClickEventMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? VapImageResolveRequestMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? VapImageResolveResultMessage {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class VapPlayerMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return VapPlayerMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return VapPlayerMessagesPigeonCodecWriter(data: data)
  }
}

class VapPlayerMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = VapPlayerMessagesPigeonCodec(readerWriter: VapPlayerMessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VapHostApi {
  func play(request: VapPlayRequestMessage) throws
  func stop(viewId: Int64) throws
  func setMute(viewId: Int64, mute: Bool) throws
  func setContentMode(viewId: Int64, mode: VapContentModeMessage) throws
  func setFrameEventsEnabled(viewId: Int64, enabled: Bool) throws
  func dispose(viewId: Int64) throws
  func getNetworkCacheSizeBytes(completion: @escaping (Result<Int64, Error>) -> Void)
  func clearNetworkCache() throws
  func pruneNetworkCacheToBytes(maxBytes: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VapHostApiSetup {
  static var codec: FlutterStandardMessageCodec { VapPlayerMessagesPigeonCodec.shared }
  /// Sets up an instance of `VapHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VapHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! VapPlayRequestMessage
        do {
          try api.play(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        do {
          try api.stop(viewId: viewIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    let setMuteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.setMute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMuteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let muteArg = args[1] as! Bool
        do {
          try api.setMute(viewId: viewIdArg, mute: muteArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMuteChannel.setMessageHandler(nil)
    }
    let setContentModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.setContentMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setContentModeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let modeArg = args[1] as! VapContentModeMessage
        do {
          try api.setContentMode(viewId: viewIdArg, mode: modeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setContentModeChannel.setMessageHandler(nil)
    }
    let setFrameEventsEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.setFrameEventsEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setFrameEventsEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let enabledArg = args[1] as! Bool
        do {
          try api.setFrameEventsEnabled(viewId: viewIdArg, enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setFrameEventsEnabledChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        do {
          try api.dispose(viewId: viewIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    let getNetworkCacheSizeBytesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.getNetworkCacheSizeBytes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getNetworkCacheSizeBytesChannel.setMessageHandler { _, reply in
        api.getNetworkCacheSizeBytes { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getNetworkCacheSizeBytesChannel.setMessageHandler(nil)
    }
    let clearNetworkCacheChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.clearNetworkCache\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearNetworkCacheChannel.setMessageHandler { _, reply in
        do {
          try api.clearNetworkCache()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearNetworkCacheChannel.setMessageHandler(nil)
    }
    let pruneNetworkCacheToBytesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.pruneNetworkCacheToBytes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pruneNetworkCacheToBytesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let maxBytesArg = args[0] as! Int64
        do {
          try api.pruneNetworkCacheToBytes(maxBytes: maxBytesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pruneNetworkCacheToBytesChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol VapEventApiProtocol {
  func onPlaybackEvent(event eventArg: VapPlaybackEventMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onResourceClick(event eventArg: VapResourceClickEventMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class VapEventApi: VapEventApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: VapPlayerMessagesPigeonCodec {
    return VapPlayerMessagesPigeonCodec.shared
  }
  func onPlaybackEvent(event eventArg: VapPlaybackEventMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.vap_player_platform_interface.VapEventApi.onPlaybackEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onResourceClick(event eventArg: VapResourceClickEventMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.vap_player_platform_interface.VapEventApi.onResourceClick\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol VapResourceApiProtocol {
  func resolveImage(request requestArg: VapImageResolveRequestMessage, completion: @escaping (Result<VapImageResolveResultMessage, PigeonError>) -> Void)
}
class VapResourceApi: VapResourceApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: VapPlayerMessagesPigeonCodec {
    return VapPlayerMessagesPigeonCodec.shared
  }
  func resolveImage(request requestArg: VapImageResolveRequestMessage, completion: @escaping (Result<VapImageResolveResultMessage, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.vap_player_platform_interface.VapResourceApi.resolveImage\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([requestArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! VapImageResolveResultMessage
        completion(.success(result))
      }
    }
  }
}
