// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.misi.vap_player_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Pigeon equivalent of VapViewType. */
enum class PlatformVapViewType(val raw: Int) {
  TEXTURE_VIEW(0),
  PLATFORM_VIEW(1);

  companion object {
    fun ofRaw(raw: Int): PlatformVapViewType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Pigeon equivalent of VapScaleType. */
enum class PlatformScaleType(val raw: Int) {
  FIT_XY(0),
  FIT_CENTER(1),
  CENTER_CROP(2);

  companion object {
    fun ofRaw(raw: Int): PlatformScaleType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Pigeon equivalent of VapResourceType. */
enum class PlatformResourceType(val raw: Int) {
  IMAGE(0),
  TEXT(1);

  companion object {
    fun ofRaw(raw: Int): PlatformResourceType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Information passed to the platform view creation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformVapViewCreationParams (
  val playerId: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformVapViewCreationParams {
      val playerId = pigeonVar_list[0] as Long
      return PlatformVapViewCreationParams(playerId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      playerId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformVapViewCreationParams
    return MessagesPigeonUtils.deepEquals(this.playerId, other.playerId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.playerId)
    return result
  }
  override fun toString(): String {
    return "PlatformVapViewCreationParams(playerId=$playerId)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformCreationOptions (
  val viewType: PlatformVapViewType,
  val enableFrameEvents: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformCreationOptions {
      val viewType = pigeonVar_list[0] as PlatformVapViewType
      val enableFrameEvents = pigeonVar_list[1] as Boolean
      return PlatformCreationOptions(viewType, enableFrameEvents)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      viewType,
      enableFrameEvents,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformCreationOptions
    return MessagesPigeonUtils.deepEquals(this.viewType, other.viewType) && MessagesPigeonUtils.deepEquals(this.enableFrameEvents, other.enableFrameEvents)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.viewType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enableFrameEvents)
    return result
  }
  override fun toString(): String {
    return "PlatformCreationOptions(viewType=$viewType, enableFrameEvents=$enableFrameEvents)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TexturePlayerIds (
  val playerId: Long,
  val textureId: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TexturePlayerIds {
      val playerId = pigeonVar_list[0] as Long
      val textureId = pigeonVar_list[1] as Long
      return TexturePlayerIds(playerId, textureId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      playerId,
      textureId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TexturePlayerIds
    return MessagesPigeonUtils.deepEquals(this.playerId, other.playerId) && MessagesPigeonUtils.deepEquals(this.textureId, other.textureId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.playerId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.textureId)
    return result
  }
  override fun toString(): String {
    return "TexturePlayerIds(playerId=$playerId, textureId=$textureId)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformPlayOptions (
  val path: String,
  /** 0 = play once, n = play n+1 times, -1 = loop forever. */
  val repeatCount: Long,
  val mute: Boolean,
  val scaleType: PlatformScaleType,
  /** Enables VAP v1 playback for mp4s that lack a `vapc` box. */
  val enableOldVersion: Boolean,
  val fps: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformPlayOptions {
      val path = pigeonVar_list[0] as String
      val repeatCount = pigeonVar_list[1] as Long
      val mute = pigeonVar_list[2] as Boolean
      val scaleType = pigeonVar_list[3] as PlatformScaleType
      val enableOldVersion = pigeonVar_list[4] as Boolean
      val fps = pigeonVar_list[5] as Long?
      return PlatformPlayOptions(path, repeatCount, mute, scaleType, enableOldVersion, fps)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      repeatCount,
      mute,
      scaleType,
      enableOldVersion,
      fps,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformPlayOptions
    return MessagesPigeonUtils.deepEquals(this.path, other.path) && MessagesPigeonUtils.deepEquals(this.repeatCount, other.repeatCount) && MessagesPigeonUtils.deepEquals(this.mute, other.mute) && MessagesPigeonUtils.deepEquals(this.scaleType, other.scaleType) && MessagesPigeonUtils.deepEquals(this.enableOldVersion, other.enableOldVersion) && MessagesPigeonUtils.deepEquals(this.fps, other.fps)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.path)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.repeatCount)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mute)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.scaleType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enableOldVersion)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fps)
    return result
  }
  override fun toString(): String {
    return "PlatformPlayOptions(path=$path, repeatCount=$repeatCount, mute=$mute, scaleType=$scaleType, enableOldVersion=$enableOldVersion, fps=$fps)"
  }
}

/**
 * A VAPX mix resource placeholder.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformVapResource (
  val id: String,
  val type: PlatformResourceType,
  val tag: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformVapResource {
      val id = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as PlatformResourceType
      val tag = pigeonVar_list[2] as String
      return PlatformVapResource(id, type, tag)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      type,
      tag,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformVapResource
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.tag, other.tag)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tag)
    return result
  }
  override fun toString(): String {
    return "PlatformVapResource(id=$id, type=$type, tag=$tag)"
  }
}

/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class PlatformVapEvent 
/**
 * Sent when the vapc config is parsed, right before rendering starts.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ConfigReadyEvent (
  val width: Long,
  val height: Long,
  val videoWidth: Long,
  val videoHeight: Long,
  val frameCount: Long,
  val fps: Long,
  val isMix: Boolean
) : PlatformVapEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConfigReadyEvent {
      val width = pigeonVar_list[0] as Long
      val height = pigeonVar_list[1] as Long
      val videoWidth = pigeonVar_list[2] as Long
      val videoHeight = pigeonVar_list[3] as Long
      val frameCount = pigeonVar_list[4] as Long
      val fps = pigeonVar_list[5] as Long
      val isMix = pigeonVar_list[6] as Boolean
      return ConfigReadyEvent(width, height, videoWidth, videoHeight, frameCount, fps, isMix)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
      videoWidth,
      videoHeight,
      frameCount,
      fps,
      isMix,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConfigReadyEvent
    return MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height) && MessagesPigeonUtils.deepEquals(this.videoWidth, other.videoWidth) && MessagesPigeonUtils.deepEquals(this.videoHeight, other.videoHeight) && MessagesPigeonUtils.deepEquals(this.frameCount, other.frameCount) && MessagesPigeonUtils.deepEquals(this.fps, other.fps) && MessagesPigeonUtils.deepEquals(this.isMix, other.isMix)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.videoWidth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.videoHeight)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.frameCount)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isMix)
    return result
  }
  override fun toString(): String {
    return "ConfigReadyEvent(width=$width, height=$height, videoWidth=$videoWidth, videoHeight=$videoHeight, frameCount=$frameCount, fps=$fps, isMix=$isMix)"
  }
}

/**
 * Sent when the first frame is rendered.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
class StartedEvent  : PlatformVapEvent() {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StartedEvent {
      return StartedEvent()
    }
  }
  fun toList(): List<Any?> {
    return listOf(
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    return true
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    return result
  }
  override fun toString(): String {
    return "StartedEvent()"
  }
}

/**
 * Sent per rendered frame, only when enableFrameEvents was requested.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FrameRenderedEvent (
  val frameIndex: Long
) : PlatformVapEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FrameRenderedEvent {
      val frameIndex = pigeonVar_list[0] as Long
      return FrameRenderedEvent(frameIndex)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      frameIndex,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FrameRenderedEvent
    return MessagesPigeonUtils.deepEquals(this.frameIndex, other.frameIndex)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.frameIndex)
    return result
  }
  override fun toString(): String {
    return "FrameRenderedEvent(frameIndex=$frameIndex)"
  }
}

/**
 * Sent when playback finishes (all repeats done, or stopped).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
class CompletedEvent  : PlatformVapEvent() {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CompletedEvent {
      return CompletedEvent()
    }
  }
  fun toList(): List<Any?> {
    return listOf(
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    return true
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    return result
  }
  override fun toString(): String {
    return "CompletedEvent()"
  }
}

/**
 * Sent when the native player has released its resources.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
class DestroyedEvent  : PlatformVapEvent() {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DestroyedEvent {
      return DestroyedEvent()
    }
  }
  fun toList(): List<Any?> {
    return listOf(
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    return true
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    return result
  }
  override fun toString(): String {
    return "DestroyedEvent()"
  }
}

/**
 * Sent when playback fails.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FailedEvent (
  val errorType: Long,
  val errorMsg: String? = null
) : PlatformVapEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FailedEvent {
      val errorType = pigeonVar_list[0] as Long
      val errorMsg = pigeonVar_list[1] as String?
      return FailedEvent(errorType, errorMsg)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      errorType,
      errorMsg,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FailedEvent
    return MessagesPigeonUtils.deepEquals(this.errorType, other.errorType) && MessagesPigeonUtils.deepEquals(this.errorMsg, other.errorMsg)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorMsg)
    return result
  }
  override fun toString(): String {
    return "FailedEvent(errorType=$errorType, errorMsg=$errorMsg)"
  }
}

/**
 * Sent when a VAPX resource is tapped.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ResourceClickedEvent (
  val resource: PlatformVapResource
) : PlatformVapEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ResourceClickedEvent {
      val resource = pigeonVar_list[0] as PlatformVapResource
      return ResourceClickedEvent(resource)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      resource,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ResourceClickedEvent
    return MessagesPigeonUtils.deepEquals(this.resource, other.resource)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.resource)
    return result
  }
  override fun toString(): String {
    return "ResourceClickedEvent(resource=$resource)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformVapViewType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformScaleType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformResourceType.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformVapViewCreationParams.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformCreationOptions.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TexturePlayerIds.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformPlayOptions.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformVapResource.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConfigReadyEvent.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StartedEvent.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FrameRenderedEvent.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CompletedEvent.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DestroyedEvent.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FailedEvent.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ResourceClickedEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PlatformVapViewType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformScaleType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformResourceType -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformVapViewCreationParams -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PlatformCreationOptions -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is TexturePlayerIds -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PlatformPlayOptions -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PlatformVapResource -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is ConfigReadyEvent -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is StartedEvent -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is FrameRenderedEvent -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is CompletedEvent -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is DestroyedEvent -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is FailedEvent -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is ResourceClickedEvent -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AndroidVapPlayerApi {
  fun initialize()
  /** Creates a player rendering into a platform view; returns the player id. */
  fun createForPlatformView(options: PlatformCreationOptions): Long
  /** Creates a player rendering into a Flutter texture; returns its ids. */
  fun createForTextureView(options: PlatformCreationOptions): TexturePlayerIds
  fun dispose(playerId: Long)

  companion object {
    /** The codec used by AndroidVapPlayerApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `AndroidVapPlayerApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AndroidVapPlayerApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_android.AndroidVapPlayerApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.initialize()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_android.AndroidVapPlayerApi.createForPlatformView$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as PlatformCreationOptions
            val wrapped: List<Any?> = try {
              listOf(api.createForPlatformView(optionsArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_android.AndroidVapPlayerApi.createForTextureView$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as PlatformCreationOptions
            val wrapped: List<Any?> = try {
              listOf(api.createForTextureView(optionsArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_android.AndroidVapPlayerApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.dispose(playerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface VapPlayerInstanceApi {
  /** Starts playback from the first frame. */
  fun play(options: PlatformPlayOptions)
  /** Stops playback. */
  fun stop()
  /** Mutes/unmutes the audio track for subsequent plays. */
  fun setMute(mute: Boolean)
  /**
   * Sets the repeat count for subsequent plays (same semantics as
   * PlatformPlayOptions.repeatCount).
   */
  fun setRepeatCount(repeatCount: Long)
  /**
   * Tells native whether a Dart resource delegate exists; when false,
   * VAPX fetch callbacks resolve to null immediately.
   */
  fun setHasResourceDelegate(hasDelegate: Boolean)

  companion object {
    /** The codec used by VapPlayerInstanceApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `VapPlayerInstanceApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VapPlayerInstanceApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_android.VapPlayerInstanceApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as PlatformPlayOptions
            val wrapped: List<Any?> = try {
              api.play(optionsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_android.VapPlayerInstanceApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_android.VapPlayerInstanceApi.setMute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val muteArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setMute(muteArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_android.VapPlayerInstanceApi.setRepeatCount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val repeatCountArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setRepeatCount(repeatCountArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_android.VapPlayerInstanceApi.setHasResourceDelegate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val hasDelegateArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setHasResourceDelegate(hasDelegateArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class VapResourceFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by VapResourceFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun resolveText(playerIdArg: Long, resourceArg: PlatformVapResource, callback: (Result<String?>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.vap_player_android.VapResourceFlutterApi.resolveText$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(playerIdArg, resourceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          val output = it[0] as String?
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun resolveImage(playerIdArg: Long, resourceArg: PlatformVapResource, callback: (Result<ByteArray?>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.vap_player_android.VapResourceFlutterApi.resolveImage$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(playerIdArg, resourceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          val output = it[0] as ByteArray?
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}

private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class VapEventsStreamHandler : MessagesPigeonEventChannelWrapper<PlatformVapEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: VapEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.vap_player_android.VapEventChannelApi.vapEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<PlatformVapEvent>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<PlatformVapEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
