// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.misi.vap_player_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object VapPlayerMessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class VapSourceTypeMessage(val raw: Int) {
  ASSET(0),
  FILE(1),
  NETWORK(2);

  companion object {
    fun ofRaw(raw: Int): VapSourceTypeMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class VapContentModeMessage(val raw: Int) {
  SCALE_TO_FILL(0),
  ASPECT_FIT(1),
  ASPECT_FILL(2);

  companion object {
    fun ofRaw(raw: Int): VapContentModeMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class VapPlaybackEventTypeMessage(val raw: Int) {
  CONFIG_READY(0),
  STARTED(1),
  FRAME(2),
  COMPLETE(3),
  DESTROY(4),
  STOPPED(5),
  FAILED(6);

  companion object {
    fun ofRaw(raw: Int): VapPlaybackEventTypeMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VapPlayRequestMessage (
  val viewId: Long? = null,
  val sourceType: VapSourceTypeMessage? = null,
  val source: String? = null,
  val assetPackage: String? = null,
  val repeatCount: Long? = null,
  val mute: Boolean? = null,
  val contentMode: VapContentModeMessage? = null,
  val fps: Long? = null,
  val frameEventsEnabled: Boolean? = null,
  val tagValues: Map<String?, String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VapPlayRequestMessage {
      val viewId = pigeonVar_list[0] as Long?
      val sourceType = pigeonVar_list[1] as VapSourceTypeMessage?
      val source = pigeonVar_list[2] as String?
      val assetPackage = pigeonVar_list[3] as String?
      val repeatCount = pigeonVar_list[4] as Long?
      val mute = pigeonVar_list[5] as Boolean?
      val contentMode = pigeonVar_list[6] as VapContentModeMessage?
      val fps = pigeonVar_list[7] as Long?
      val frameEventsEnabled = pigeonVar_list[8] as Boolean?
      val tagValues = pigeonVar_list[9] as Map<String?, String?>?
      return VapPlayRequestMessage(viewId, sourceType, source, assetPackage, repeatCount, mute, contentMode, fps, frameEventsEnabled, tagValues)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      viewId,
      sourceType,
      source,
      assetPackage,
      repeatCount,
      mute,
      contentMode,
      fps,
      frameEventsEnabled,
      tagValues,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VapPlayRequestMessage
    return VapPlayerMessagesPigeonUtils.deepEquals(this.viewId, other.viewId) && VapPlayerMessagesPigeonUtils.deepEquals(this.sourceType, other.sourceType) && VapPlayerMessagesPigeonUtils.deepEquals(this.source, other.source) && VapPlayerMessagesPigeonUtils.deepEquals(this.assetPackage, other.assetPackage) && VapPlayerMessagesPigeonUtils.deepEquals(this.repeatCount, other.repeatCount) && VapPlayerMessagesPigeonUtils.deepEquals(this.mute, other.mute) && VapPlayerMessagesPigeonUtils.deepEquals(this.contentMode, other.contentMode) && VapPlayerMessagesPigeonUtils.deepEquals(this.fps, other.fps) && VapPlayerMessagesPigeonUtils.deepEquals(this.frameEventsEnabled, other.frameEventsEnabled) && VapPlayerMessagesPigeonUtils.deepEquals(this.tagValues, other.tagValues)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.viewId)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.sourceType)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.source)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.assetPackage)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.repeatCount)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.mute)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.contentMode)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.fps)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.frameEventsEnabled)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.tagValues)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VapPlaybackEventMessage (
  val viewId: Long? = null,
  val type: VapPlaybackEventTypeMessage? = null,
  val frameIndex: Long? = null,
  val width: Long? = null,
  val height: Long? = null,
  val fps: Long? = null,
  val isMix: Boolean? = null,
  val errorCode: Long? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VapPlaybackEventMessage {
      val viewId = pigeonVar_list[0] as Long?
      val type = pigeonVar_list[1] as VapPlaybackEventTypeMessage?
      val frameIndex = pigeonVar_list[2] as Long?
      val width = pigeonVar_list[3] as Long?
      val height = pigeonVar_list[4] as Long?
      val fps = pigeonVar_list[5] as Long?
      val isMix = pigeonVar_list[6] as Boolean?
      val errorCode = pigeonVar_list[7] as Long?
      val errorMessage = pigeonVar_list[8] as String?
      return VapPlaybackEventMessage(viewId, type, frameIndex, width, height, fps, isMix, errorCode, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      viewId,
      type,
      frameIndex,
      width,
      height,
      fps,
      isMix,
      errorCode,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VapPlaybackEventMessage
    return VapPlayerMessagesPigeonUtils.deepEquals(this.viewId, other.viewId) && VapPlayerMessagesPigeonUtils.deepEquals(this.type, other.type) && VapPlayerMessagesPigeonUtils.deepEquals(this.frameIndex, other.frameIndex) && VapPlayerMessagesPigeonUtils.deepEquals(this.width, other.width) && VapPlayerMessagesPigeonUtils.deepEquals(this.height, other.height) && VapPlayerMessagesPigeonUtils.deepEquals(this.fps, other.fps) && VapPlayerMessagesPigeonUtils.deepEquals(this.isMix, other.isMix) && VapPlayerMessagesPigeonUtils.deepEquals(this.errorCode, other.errorCode) && VapPlayerMessagesPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.viewId)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.frameIndex)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.height)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.fps)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.isMix)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.errorMessage)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VapResourceClickEventMessage (
  val viewId: Long? = null,
  val resourceId: String? = null,
  val tag: String? = null,
  val x: Double? = null,
  val y: Double? = null,
  val width: Double? = null,
  val height: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VapResourceClickEventMessage {
      val viewId = pigeonVar_list[0] as Long?
      val resourceId = pigeonVar_list[1] as String?
      val tag = pigeonVar_list[2] as String?
      val x = pigeonVar_list[3] as Double?
      val y = pigeonVar_list[4] as Double?
      val width = pigeonVar_list[5] as Double?
      val height = pigeonVar_list[6] as Double?
      return VapResourceClickEventMessage(viewId, resourceId, tag, x, y, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      viewId,
      resourceId,
      tag,
      x,
      y,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VapResourceClickEventMessage
    return VapPlayerMessagesPigeonUtils.deepEquals(this.viewId, other.viewId) && VapPlayerMessagesPigeonUtils.deepEquals(this.resourceId, other.resourceId) && VapPlayerMessagesPigeonUtils.deepEquals(this.tag, other.tag) && VapPlayerMessagesPigeonUtils.deepEquals(this.x, other.x) && VapPlayerMessagesPigeonUtils.deepEquals(this.y, other.y) && VapPlayerMessagesPigeonUtils.deepEquals(this.width, other.width) && VapPlayerMessagesPigeonUtils.deepEquals(this.height, other.height)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.viewId)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.resourceId)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.tag)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.x)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.y)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.height)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VapImageResolveRequestMessage (
  val viewId: Long? = null,
  val resourceId: String? = null,
  val tag: String? = null,
  val type: String? = null,
  val loadType: String? = null,
  val width: Long? = null,
  val height: Long? = null,
  val url: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VapImageResolveRequestMessage {
      val viewId = pigeonVar_list[0] as Long?
      val resourceId = pigeonVar_list[1] as String?
      val tag = pigeonVar_list[2] as String?
      val type = pigeonVar_list[3] as String?
      val loadType = pigeonVar_list[4] as String?
      val width = pigeonVar_list[5] as Long?
      val height = pigeonVar_list[6] as Long?
      val url = pigeonVar_list[7] as String?
      return VapImageResolveRequestMessage(viewId, resourceId, tag, type, loadType, width, height, url)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      viewId,
      resourceId,
      tag,
      type,
      loadType,
      width,
      height,
      url,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VapImageResolveRequestMessage
    return VapPlayerMessagesPigeonUtils.deepEquals(this.viewId, other.viewId) && VapPlayerMessagesPigeonUtils.deepEquals(this.resourceId, other.resourceId) && VapPlayerMessagesPigeonUtils.deepEquals(this.tag, other.tag) && VapPlayerMessagesPigeonUtils.deepEquals(this.type, other.type) && VapPlayerMessagesPigeonUtils.deepEquals(this.loadType, other.loadType) && VapPlayerMessagesPigeonUtils.deepEquals(this.width, other.width) && VapPlayerMessagesPigeonUtils.deepEquals(this.height, other.height) && VapPlayerMessagesPigeonUtils.deepEquals(this.url, other.url)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.viewId)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.resourceId)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.tag)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.loadType)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.height)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.url)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VapImageResolveResultMessage (
  val imageBytes: ByteArray? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VapImageResolveResultMessage {
      val imageBytes = pigeonVar_list[0] as ByteArray?
      val errorMessage = pigeonVar_list[1] as String?
      return VapImageResolveResultMessage(imageBytes, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      imageBytes,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VapImageResolveResultMessage
    return VapPlayerMessagesPigeonUtils.deepEquals(this.imageBytes, other.imageBytes) && VapPlayerMessagesPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.imageBytes)
    result = 31 * result + VapPlayerMessagesPigeonUtils.deepHash(this.errorMessage)
    return result
  }
}
private open class VapPlayerMessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VapSourceTypeMessage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VapContentModeMessage.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VapPlaybackEventTypeMessage.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VapPlayRequestMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VapPlaybackEventMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VapResourceClickEventMessage.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VapImageResolveRequestMessage.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VapImageResolveResultMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VapSourceTypeMessage -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is VapContentModeMessage -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is VapPlaybackEventTypeMessage -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is VapPlayRequestMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is VapPlaybackEventMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is VapResourceClickEventMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is VapImageResolveRequestMessage -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is VapImageResolveResultMessage -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface VapHostApi {
  fun play(request: VapPlayRequestMessage)
  fun stop(viewId: Long)
  fun setMute(viewId: Long, mute: Boolean)
  fun setContentMode(viewId: Long, mode: VapContentModeMessage)
  fun setFrameEventsEnabled(viewId: Long, enabled: Boolean)
  fun dispose(viewId: Long)
  fun getNetworkCacheSizeBytes(callback: (Result<Long>) -> Unit)
  fun clearNetworkCache()
  fun pruneNetworkCacheToBytes(maxBytes: Long)
  fun getNetworkAutoEvictionMaxBytes(callback: (Result<Long>) -> Unit)
  fun setNetworkAutoEvictionMaxBytes(maxBytes: Long)

  companion object {
    /** The codec used by VapHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      VapPlayerMessagesPigeonCodec()
    }
    /** Sets up an instance of `VapHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VapHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as VapPlayRequestMessage
            val wrapped: List<Any?> = try {
              api.play(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              VapPlayerMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.stop(viewIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              VapPlayerMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.setMute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val muteArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setMute(viewIdArg, muteArg)
              listOf(null)
            } catch (exception: Throwable) {
              VapPlayerMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.setContentMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val modeArg = args[1] as VapContentModeMessage
            val wrapped: List<Any?> = try {
              api.setContentMode(viewIdArg, modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              VapPlayerMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.setFrameEventsEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val enabledArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setFrameEventsEnabled(viewIdArg, enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              VapPlayerMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.dispose(viewIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              VapPlayerMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.getNetworkCacheSizeBytes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getNetworkCacheSizeBytes{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VapPlayerMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(VapPlayerMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.clearNetworkCache$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearNetworkCache()
              listOf(null)
            } catch (exception: Throwable) {
              VapPlayerMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.pruneNetworkCacheToBytes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val maxBytesArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.pruneNetworkCacheToBytes(maxBytesArg)
              listOf(null)
            } catch (exception: Throwable) {
              VapPlayerMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.getNetworkAutoEvictionMaxBytes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getNetworkAutoEvictionMaxBytes{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VapPlayerMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(VapPlayerMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.setNetworkAutoEvictionMaxBytes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val maxBytesArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setNetworkAutoEvictionMaxBytes(maxBytesArg)
              listOf(null)
            } catch (exception: Throwable) {
              VapPlayerMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class VapEventApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by VapEventApi. */
    val codec: MessageCodec<Any?> by lazy {
      VapPlayerMessagesPigeonCodec()
    }
  }
  fun onPlaybackEvent(eventArg: VapPlaybackEventMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.vap_player_platform_interface.VapEventApi.onPlaybackEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(VapPlayerMessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onResourceClick(eventArg: VapResourceClickEventMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.vap_player_platform_interface.VapEventApi.onResourceClick$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(VapPlayerMessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class VapResourceApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by VapResourceApi. */
    val codec: MessageCodec<Any?> by lazy {
      VapPlayerMessagesPigeonCodec()
    }
  }
  fun resolveImage(requestArg: VapImageResolveRequestMessage, callback: (Result<VapImageResolveResultMessage>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.vap_player_platform_interface.VapResourceApi.resolveImage$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as VapImageResolveResultMessage
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(VapPlayerMessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
