name: flutter_vap_player_example
description: Demonstrates how to use the flutter_vap_player plugin.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_vap_player:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  vap_player_android:
    path: ../../vap_player_android
  vap_player_ios:
    path: ../../vap_player_ios
  vap_player_platform_interface:
    path: ../../vap_player_platform_interface

flutter:
  uses-material-design: true
  assets:
    - assets/vap/
    - assets/img/
