// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum VapSourceTypeMessage {
  asset,
  file,
  network,
}

enum VapContentModeMessage {
  scaleToFill,
  aspectFit,
  aspectFill,
}

enum VapPlaybackEventTypeMessage {
  configReady,
  start,
  frame,
  complete,
  destroy,
  stopped,
  failed,
}

class VapPlayRequestMessage {
  VapPlayRequestMessage({
    this.viewId,
    this.sourceType,
    this.source,
    this.assetPackage,
    this.repeatCount,
    this.mute,
    this.contentMode,
    this.fps,
    this.frameEventsEnabled,
    this.tagValues,
  });

  int? viewId;

  VapSourceTypeMessage? sourceType;

  String? source;

  String? assetPackage;

  int? repeatCount;

  bool? mute;

  VapContentModeMessage? contentMode;

  int? fps;

  bool? frameEventsEnabled;

  Map<String?, String?>? tagValues;

  List<Object?> _toList() {
    return <Object?>[
      viewId,
      sourceType,
      source,
      assetPackage,
      repeatCount,
      mute,
      contentMode,
      fps,
      frameEventsEnabled,
      tagValues,
    ];
  }

  Object encode() {
    return _toList();  }

  static VapPlayRequestMessage decode(Object result) {
    result as List<Object?>;
    return VapPlayRequestMessage(
      viewId: result[0] as int?,
      sourceType: result[1] as VapSourceTypeMessage?,
      source: result[2] as String?,
      assetPackage: result[3] as String?,
      repeatCount: result[4] as int?,
      mute: result[5] as bool?,
      contentMode: result[6] as VapContentModeMessage?,
      fps: result[7] as int?,
      frameEventsEnabled: result[8] as bool?,
      tagValues: (result[9] as Map<Object?, Object?>?)?.cast<String?, String?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VapPlayRequestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(viewId, other.viewId) && _deepEquals(sourceType, other.sourceType) && _deepEquals(source, other.source) && _deepEquals(assetPackage, other.assetPackage) && _deepEquals(repeatCount, other.repeatCount) && _deepEquals(mute, other.mute) && _deepEquals(contentMode, other.contentMode) && _deepEquals(fps, other.fps) && _deepEquals(frameEventsEnabled, other.frameEventsEnabled) && _deepEquals(tagValues, other.tagValues);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class VapPlaybackEventMessage {
  VapPlaybackEventMessage({
    this.viewId,
    this.type,
    this.frameIndex,
    this.width,
    this.height,
    this.fps,
    this.isMix,
    this.errorCode,
    this.errorMessage,
  });

  int? viewId;

  VapPlaybackEventTypeMessage? type;

  int? frameIndex;

  int? width;

  int? height;

  int? fps;

  bool? isMix;

  int? errorCode;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      viewId,
      type,
      frameIndex,
      width,
      height,
      fps,
      isMix,
      errorCode,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static VapPlaybackEventMessage decode(Object result) {
    result as List<Object?>;
    return VapPlaybackEventMessage(
      viewId: result[0] as int?,
      type: result[1] as VapPlaybackEventTypeMessage?,
      frameIndex: result[2] as int?,
      width: result[3] as int?,
      height: result[4] as int?,
      fps: result[5] as int?,
      isMix: result[6] as bool?,
      errorCode: result[7] as int?,
      errorMessage: result[8] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VapPlaybackEventMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(viewId, other.viewId) && _deepEquals(type, other.type) && _deepEquals(frameIndex, other.frameIndex) && _deepEquals(width, other.width) && _deepEquals(height, other.height) && _deepEquals(fps, other.fps) && _deepEquals(isMix, other.isMix) && _deepEquals(errorCode, other.errorCode) && _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class VapResourceClickEventMessage {
  VapResourceClickEventMessage({
    this.viewId,
    this.resourceId,
    this.tag,
    this.x,
    this.y,
    this.width,
    this.height,
  });

  int? viewId;

  String? resourceId;

  String? tag;

  double? x;

  double? y;

  double? width;

  double? height;

  List<Object?> _toList() {
    return <Object?>[
      viewId,
      resourceId,
      tag,
      x,
      y,
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static VapResourceClickEventMessage decode(Object result) {
    result as List<Object?>;
    return VapResourceClickEventMessage(
      viewId: result[0] as int?,
      resourceId: result[1] as String?,
      tag: result[2] as String?,
      x: result[3] as double?,
      y: result[4] as double?,
      width: result[5] as double?,
      height: result[6] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VapResourceClickEventMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(viewId, other.viewId) && _deepEquals(resourceId, other.resourceId) && _deepEquals(tag, other.tag) && _deepEquals(x, other.x) && _deepEquals(y, other.y) && _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class VapImageResolveRequestMessage {
  VapImageResolveRequestMessage({
    this.viewId,
    this.resourceId,
    this.tag,
    this.type,
    this.loadType,
    this.width,
    this.height,
    this.url,
  });

  int? viewId;

  String? resourceId;

  String? tag;

  String? type;

  String? loadType;

  int? width;

  int? height;

  String? url;

  List<Object?> _toList() {
    return <Object?>[
      viewId,
      resourceId,
      tag,
      type,
      loadType,
      width,
      height,
      url,
    ];
  }

  Object encode() {
    return _toList();  }

  static VapImageResolveRequestMessage decode(Object result) {
    result as List<Object?>;
    return VapImageResolveRequestMessage(
      viewId: result[0] as int?,
      resourceId: result[1] as String?,
      tag: result[2] as String?,
      type: result[3] as String?,
      loadType: result[4] as String?,
      width: result[5] as int?,
      height: result[6] as int?,
      url: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VapImageResolveRequestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(viewId, other.viewId) && _deepEquals(resourceId, other.resourceId) && _deepEquals(tag, other.tag) && _deepEquals(type, other.type) && _deepEquals(loadType, other.loadType) && _deepEquals(width, other.width) && _deepEquals(height, other.height) && _deepEquals(url, other.url);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class VapImageResolveResultMessage {
  VapImageResolveResultMessage({
    this.imageBytes,
    this.errorMessage,
  });

  Uint8List? imageBytes;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      imageBytes,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static VapImageResolveResultMessage decode(Object result) {
    result as List<Object?>;
    return VapImageResolveResultMessage(
      imageBytes: result[0] as Uint8List?,
      errorMessage: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VapImageResolveResultMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(imageBytes, other.imageBytes) && _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is VapSourceTypeMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is VapContentModeMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is VapPlaybackEventTypeMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is VapPlayRequestMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is VapPlaybackEventMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is VapResourceClickEventMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is VapImageResolveRequestMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is VapImageResolveResultMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : VapSourceTypeMessage.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : VapContentModeMessage.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : VapPlaybackEventTypeMessage.values[value];
      case 132:
        return VapPlayRequestMessage.decode(readValue(buffer)!);
      case 133:
        return VapPlaybackEventMessage.decode(readValue(buffer)!);
      case 134:
        return VapResourceClickEventMessage.decode(readValue(buffer)!);
      case 135:
        return VapImageResolveRequestMessage.decode(readValue(buffer)!);
      case 136:
        return VapImageResolveResultMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class VapHostApi {
  /// Constructor for [VapHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VapHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> play(VapPlayRequestMessage request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.play$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stop(int viewId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[viewId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setMute(int viewId, bool mute) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.setMute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[viewId, mute]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setContentMode(int viewId, VapContentModeMessage mode) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.setContentMode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[viewId, mode]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setFrameEventsEnabled(int viewId, bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.setFrameEventsEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[viewId, enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> dispose(int viewId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[viewId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<int> getNetworkCacheSizeBytes() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.getNetworkCacheSizeBytes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<void> clearNetworkCache() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.clearNetworkCache$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> pruneNetworkCacheToBytes(int maxBytes) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vap_player_platform_interface.VapHostApi.pruneNetworkCacheToBytes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[maxBytes]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class VapEventApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onPlaybackEvent(VapPlaybackEventMessage event);

  void onResourceClick(VapResourceClickEventMessage event);

  static void setUp(VapEventApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.vap_player_platform_interface.VapEventApi.onPlaybackEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final VapPlaybackEventMessage arg_event = args[0]! as VapPlaybackEventMessage;
          try {
            api.onPlaybackEvent(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.vap_player_platform_interface.VapEventApi.onResourceClick$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final VapResourceClickEventMessage arg_event = args[0]! as VapResourceClickEventMessage;
          try {
            api.onResourceClick(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

abstract class VapResourceApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<VapImageResolveResultMessage> resolveImage(VapImageResolveRequestMessage request);

  static void setUp(VapResourceApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.vap_player_platform_interface.VapResourceApi.resolveImage$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final VapImageResolveRequestMessage arg_request = args[0]! as VapImageResolveRequestMessage;
          try {
            final VapImageResolveResultMessage output = await api.resolveImage(arg_request);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
